[project]
name = "sqlalchemy-cruder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.11",
    "mypy>=1.15.0",
    "sqlalchemy>=2.0.38",
]
